puts "The students of my cohort at Makers Academy"
puts "--------"
puts "Bibiana Cristofol"
puts "Gus Powell"
puts "Gabe"
puts "Danielle"
puts "Charlie Walsh"
puts "David Blake"
puts "Jack Rubio"
puts "Oliver Lucas"
puts "Luke"
puts "Matteo Manzo"
puts "Marcus de Wilde"
puts "Huy Le"
puts "Steph Oldcorn"
puts "Ptolemy"
puts "Sanda Golcea"
puts "Richard Ighodaro"
puts "Andy Newman"
puts "Marcin"
puts "Jacob Mitchinson"
puts "Emily Sas"
